name: Deploy Yii2 App

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: dineshvaishnav/yii2-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t $DOCKER_IMAGE:latest .
        docker push $DOCKER_IMAGE:latest

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker service update --image $DOCKER_IMAGE:latest yii2-app || \
          docker service create --name yii2-app --replicas 1 --publish published=8080,target=80 $DOCKER_IMAGE:latest
